.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"	@(#)sl.1
.\"
.Dd October 22, 2022
.Dt SL 1
.Os
.Sh NAME
.Nm sl
.Nd animations for accidental typos to list files
.Sh SYNOPSIS
.Nm sl
.Op Fl acdeFlw
.Sh DESCRIPTION
.Nm sl
displays animations aimed to correct users who accidentally enter
.Nm sl
instead of ls.
.Nm sl
stands for Steam Locomotive.
.Bl -tag -width -indent
.It Fl a
Creates an accident.
People cry for help.
.It Fl c
Displays C51 instead of D51.
.It Fl d
Alternates colors during animation (aka disco mode).
.It Fl e
Enables escaping with Ctrl + C.
.It Fl F
Speeds up the annimation, like the galaxy express 999.
.It Fl G
It's French, like Oscar.
.It Fl Op n
Specifies the number of cars that will be displayed.
.Ar n
refers to the exact number of cars that will be displayed.
.It Fl l
Uses little version of the animation.
.It Fl w
Windy day.
Locomotive moves faster.
.It Fl v
Prints the version & last updated info.
.El
.Sh SEE ALSO
.Xr ls 1
.Sh BUGS
It sometimes lists directory contents.
.Sh AUTHOR
.An Toyoda Masashi Aq Mt mtoyoda@acm.org
